"""cambio en nombres de tablas

Revision ID: 0e7ea0b9c448
Revises: cdf6efdb7314
Create Date: 2020-06-30 18:10:03.295014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7ea0b9c448'
down_revision = 'cdf6efdb7314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_version',
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ovn', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_job',
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ovn', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('task_version_id', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NOT_PROCESSED', 'PROCESSED', 'ERRORED', 'PROCESSING', name='status'), nullable=False),
    sa.Column('execution_status', sa.String(length=20), nullable=True),
    sa.CheckConstraint("status IN ('NOT_PROCESSED','PROCESSED','PROCESSING','ERRORED')", name='bot_job_status_ck'),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.ForeignKeyConstraint(['task_version_id'], ['task_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('botJob')
    op.drop_table('taskVersion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskVersion',
    sa.Column('creation_date', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_date', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('ovn', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('task_body', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.VARCHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('botJob',
    sa.Column('creation_date', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_date', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('ovn', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bot_id', sa.INTEGER(), nullable=False),
    sa.Column('task_version_id', sa.INTEGER(), nullable=False),
    sa.Column('parameters', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.ForeignKeyConstraint(['task_version_id'], ['taskVersion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bot_job')
    op.drop_table('task_version')
    # ### end Alembic commands ###
