"""se agregó la columna job_type

Revision ID: 30ee01d7746b
Revises: eabe70edf709
Create Date: 2020-07-17 09:36:43.289795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '30ee01d7746b'
down_revision = 'eabe70edf709'
branch_labels = None
depends_on = None


def upgrade():

    enum = postgresql.ENUM('IMMEDIATE', 'SCHEDULED', name='botjobtype')
    enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.Enum('IMMEDIATE', 'SCHEDULED', name='botjobtype'), nullable=True))

    with op.batch_alter_table('bot_scheduled_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_scheduled_job_queue_identifier'), ['queue_identifier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_scheduled_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_scheduled_job_queue_identifier'))

    with op.batch_alter_table('bot_job', schema=None) as batch_op:
        batch_op.drop_column('job_type')

    # ### end Alembic commands ###
