"""se renombró la clase BotHearbeat a BotHeartbeat

Revision ID: 656331b97529
Revises: af5196492fef
Create Date: 2020-06-29 20:59:19.057105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656331b97529'
down_revision = 'af5196492fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_heartbeat',
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ovn', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bot_hearbeat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_hearbeat',
    sa.Column('creation_date', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_date', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('ovn', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bot_id', sa.INTEGER(), nullable=True),
    sa.Column('registered_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bot_heartbeat')
    # ### end Alembic commands ###
