"""address, bot, botheartbeat, paremeter

Revision ID: af5196492fef
Revises: bfbee9c02dd3
Create Date: 2020-06-29 20:26:58.408520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5196492fef'
down_revision = 'bfbee9c02dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    parameter_table = op.create_table('parameter',
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ovn', sa.Integer(), nullable=True),
    sa.Column('parameter_key', sa.String(length=50), nullable=False),
    sa.Column('parameter_desc', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.String(length=1), nullable=False),
    sa.Column('param_type', sa.String(length=20), nullable=False),
    sa.Column('varchar_value', sa.String(length=3000), nullable=True),
    sa.Column('number_value', sa.Float(), nullable=True),
    sa.Column('date_value', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('parameter_key')
    )
    op.create_table('address',
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ovn', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('municipality', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=300), nullable=False),
    sa.Column('postal_code', sa.String(length=5), nullable=False),
    sa.Column('interior_number', sa.String(length=10), nullable=False),
    sa.Column('exterior_number', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot',
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ovn', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bot_secret', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_hearbeat',
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ovn', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_emai_uk', ['email'])

    # ### end Alembic commands ###
    op.bulk_insert(parameter_table,
        [
            {
                'parameter_key' : 'printscreen_resource'
                ,'parameter_desc': 'Resource to upload screen evidence'
                ,'is_active': 'V'
                ,'param_type': 'VARCHAR'
                ,'varchar_value': '{ "fields": { "job_id": "__JOB_ID__", "extension": "png" }, "url": "__BASE_URI__/api/job/failure" }'
                ,'created_by': -1
                ,'updated_by': -1
            },
            {
                'parameter_key' : 'jobevidence_resource'
                ,'parameter_desc': 'Resource to upload the job script'
                ,'is_active': 'V'
                ,'param_type': 'VARCHAR'
                ,'varchar_value': '{ "fields": { "job_id": "__JOB_ID__", "extension": "ipynb" }, "url": "__BASE_URI__/api/job/evidence" }'
                ,'created_by': -1
                ,'updated_by': -1
            }
        ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_emai_uk', type_='unique')

    op.drop_table('bot_hearbeat')
    op.drop_table('bot')
    op.drop_table('address')
    op.drop_table('parameter')
    # ### end Alembic commands ###
