"""Se agrego campo queue_identifier a BotScheduledJob

Revision ID: eabe70edf709
Revises: fe505029da8a
Create Date: 2020-07-10 18:16:12.710771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabe70edf709'
down_revision = 'fe505029da8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_scheduled_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue_identifier', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_scheduled_job', schema=None) as batch_op:
        batch_op.drop_column('queue_identifier')

    # ### end Alembic commands ###
