"""bot scheduled job, BaseIsActiveMixin

Revision ID: fe505029da8a
Revises: bbd655117bd6
Create Date: 2020-07-09 13:45:34.302568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe505029da8a'
down_revision = 'bbd655117bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_scheduled_job',
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ovn', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Enum('V', 'F', name='isactive'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NOT_PROCESSED', 'COMPLETED', 'N_REPEAT_LEFT', 'PROCESSING', name='scheduledjobstatus'), nullable=False),
    sa.Column('when', sa.String(length=100), nullable=False),
    sa.Column('until', sa.DateTime(), nullable=True),
    sa.Column('repeat', sa.Integer(), nullable=True),
    sa.CheckConstraint("is_active IN ('V','F')", name='bot_scheduled_job_is_active_ck'),
    sa.CheckConstraint("status IN ('NOT_PROCESSED','COMPLETED','N_REPEAT_LEFT', 'PROCESSING')", name='bot_scheduled_job_status_ck'),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Enum('V', 'F', name='isactive'), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.VARCHAR(length=1), nullable=False))

    with op.batch_alter_table('bot_task', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    op.drop_table('bot_scheduled_job')
    # ### end Alembic commands ###
