"""modelo BotJobEvidence

Revision ID: fec2ee61d225
Revises: 0e7ea0b9c448
Create Date: 2020-07-02 15:30:57.181434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec2ee61d225'
down_revision = '0e7ea0b9c448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_job_evidence',
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ovn', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_job_id', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['bot_job_id'], ['bot_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_job_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_job_evidence_bot_job_id'), ['bot_job_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_job_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_job_evidence_bot_job_id'))

    op.drop_table('bot_job_evidence')
    # ### end Alembic commands ###
